### ISSUE TITLE
Some patterns generate unexpected redundant code

### ISSUE THREAD

**Issue by mitranim** [BenjaminSchaaf/sbnf#11]
For some recursive or mutually recursive rules, the resulting code has redundancies that a human-written version wouldn't have. Unfortunately I'm too inexperienced to tell whether it's SBNF or my rules.

Consider this over-simplified example:

```
main = `[` (~main)* ~`]`;
```

SBNF generates the following contexts:

```yaml
contexts:
  # Rule: main
  main:
    - match: '\['
      set: main|0
    - match: '\S'
      scope: invalid.illegal.mock
  # Rule: main
  main|0:
    - match: '\['
      push: main|0
    - match: '\]'
      pop: true
```

The human version would define an additional context included in both places, and re-include `main` to avoid duplication:

```yaml
contexts:
  main:
    - include: block
  block:
    - match: '\['
      push: pop-block
  pop-block:
    - match: '\]'
      pop: true
    - include: main
```

This becomes a big deal in syntaxes with many mutually recursive patterns. I just translated a work-in-progress LLVM syntax, whose `.sublime-syntax` version has 169 total lines, and the SBNF output has 1211 lines because many rules got duplicated inline instead of using `include`. Can provide the code if needed.

To better demonstrate duplication, consider this hypothetical over-simplified syntax for S-expressions (untested):

```
main = (~symbol|dot|list)*;
symbol = '[^\s().]'*;
dot = `.`;
list = `(` (~main)* ~`)`;
```

The SBNF output clearly has duplication we don't want:

```yaml
contexts:
  # Rule: list
  list|0:
    - match: '[^\s().]'
      push: [main, symbol|0]
    - match: '\.'
      push: main
    - match: '\('
      push: [main, list|0]
    - match: '\)'
      pop: true
  # Rule: main
  main:
    - match: '[^\s().]'
      push: symbol|0
    - match: '\.'
    - match: '\('
      push: list|0
  # Rule: symbol
  symbol|0:
    - match: '[^\s().]'
    - match: '(?=\S)'
      pop: true
```

I hope I'm just doing this wrong. 🙂 Suggestions are appreciated. That said, even if the compiler already supports the "right" ways of doing this, it seems too easy to it the "wrong" way that still _seems_ to work but generates inferior output. We might want to figure out how to safeguard the users from this.
