### ISSUE TITLE
Rule interpolation

### ISSUE THREAD

**Issue by mitranim** [BenjaminSchaaf/sbnf#12]
In `.sublime-syntax`, it's common to define variables to include them into regexp patterns:

```yaml
variables:
  exponent: '[Ee][+-]?'
  
match-floats:
  - match: \d+({{exponent}})\d+
  - match: \d+(\.)\d+(?:({{exponent}})\d+)?
```

SBNF supports interpolation, which is currently limited to parameters. I would appreciate the ability to interpolate rules. The compiler could allow this for rules that consist _only_ of a single regexp or literal string. This would allow the following:

```
exponent = '[Ee][+-]?';

floats =
  '\d+(#[exponent])\d+' |
  '\d+(\.)\d+(?:(#[exponent])\d+)?';
```

_Technically_, currently we can reuse regexp patterns by passing them as parameters:

```
floats = floats_impl['[Ee][+-]?'];

floats_impl[exp] =
  '\d+(#[exp])\d+' |
  '\d+(\.)\d+(?:(#[exp])\d+)?';
```

Personally, I find the version with rule interpolation much cleaner and more intuitive. Also, I don't see how the parametrized approach would work when wanting to reuse the same pattern across several unrelated rules.
