### ISSUE TITLE
Wrong generated code

### ISSUE THREAD

**Issue by AmjadHD** [BenjaminSchaaf/sbnf#18]
```bnf
RSTR_LIT =
  '([rR])(")'{
    meta.string,
    1: storage.type.string,
    2: string.quoted.double punctuation.definition.string.begin
  }
  rstr_lit_impl;

rstr_lit_impl{meta.string string.quoted.double} =
    (~`""`{constant.character.escape.double-quote})*
    ~('"'{punctuation.definition.string.end} | 
      '\n'{invalid.illegal.unclosed-string});
```
produces:
```yaml
contexts:
  main:
    ...
    - match: '([rR])(")'
      scope: meta.string.xmpl
      captures:
        1: storage.type.string.xmpl
        2: string.quoted.double.xmpl punctuation.definition.string.begin.xmpl
      set: RSTR_LIT|0
    ...

  RSTR_LIT|0:
    - match: '""'
      scope: meta.string.xmpl string.quoted.double.xmpl constant.character.escape.double-quote.xmpl
      set: rstr_lit_impl|0
    - match: '"'
      scope: meta.string.xmpl string.quoted.double.xmpl punctuation.definition.string.end.xmpl
      pop: true
    - match: '\n'
      scope: meta.string.xmpl string.quoted.double.xmpl invalid.illegal.unclosed-string.xmpl
      pop: true
    - match: '(?=\S)'
      set: RSTR_LIT|1

  RSTR_LIT|1:
    - match: '""'
      scope: meta.string.xmpl string.quoted.double.xmpl constant.character.escape.double-quote.xmpl
      set: rstr_lit_impl|0
    - match: '"'
      scope: meta.string.xmpl string.quoted.double.xmpl punctuation.definition.string.end.xmpl
      pop: true
    - match: '\n'
      scope: meta.string.xmpl string.quoted.double.xmpl invalid.illegal.unclosed-string.xmpl
      pop: true

  rstr_lit_impl|0:
    - meta_content_scope: meta.string.xmpl string.quoted.double.xmpl
    - match: '""'
      scope: meta.string.xmpl string.quoted.double.xmpl constant.character.escape.double-quote.xmpl
    - match: '"'
      scope: meta.string.xmpl string.quoted.double.xmpl punctuation.definition.string.end.xmpl
      pop: true
    - match: '\n'
      scope: meta.string.xmpl string.quoted.double.xmpl invalid.illegal.unclosed-string.xmpl
      pop: true
```
and doesn't work:
![scope](https://cdn.discordapp.com/attachments/280157067396775936/788117216078856243/unknown.png)
it should produce:
```yaml
contexts:
  main:
    ...
    - match: '([rR])(")'
      scope: meta.string.xmpl
      captures:
        1: storage.type.string.xmpl
        2: string.quoted.double.xmpl punctuation.definition.string.begin.xmpl
      set: rstr_lit_impl|0
    ...

  rstr_lit_impl|0:
    - meta_content_scope: meta.string.xmpl string.quoted.double.xmpl
    - match: '""'
      scope: meta.string.xmpl string.quoted.double.xmpl constant.character.escape.double-quote.xmpl
    - match: '"'
      scope: meta.string.xmpl string.quoted.double.xmpl punctuation.definition.string.end.xmpl
      pop: true
    - match: '\n'
      scope: meta.string.xmpl string.quoted.double.xmpl invalid.illegal.unclosed-string.xmpl
      pop: true
```
