### ISSUE TITLE
Unexpected result with recursive rules?

### ISSUE THREAD

**Issue by nuchi** [BenjaminSchaaf/sbnf#23]
Using sbnf version 0.4.0. EDIT: same on master

```sbnf
main = expr;
expr = primitive (`+` primitive)*;
primitive = num | `(` expr `)`;
num = '\d+'{constant.numeric};
```

Sample highlighting:
![image](https://user-images.githubusercontent.com/16771734/135910564-fa73b50a-ec3d-4195-9181-c7241d3f3e8e.png)

Expected result: the first `(` should be `invalid.illegal`.
Actual result: `(` matches in `main`.

<details><summary>compiled output</summary>

```yaml
%YAML 1.2
---
# http://www.sublimetext.com/docs/syntax.html
version: 2
name: test
file_extensions:
  - test
scope: source.test
contexts:
  # Rule: expr
  expr|0:
    - match: '\+'
      push: expr|1
    - match: '(?=\S)'
      pop: true
  # Rule: expr
  expr|1:
    - match: '\d+'
      scope: constant.numeric.test
      pop: true
    - match: '\('
      set: primitive|0
    - match: '\S'
      scope: invalid.illegal.test
      pop: true
  # Rule: main
  main:
    - match: '\d+'
      scope: constant.numeric.test
      set: expr|0
    - match: '\('
      set: [expr|0, primitive|0]
    - match: '\S'
      scope: invalid.illegal.test
  # Rule: primitive
  primitive|0:
    - match: '\d+'
      scope: constant.numeric.test
      set: [primitive|1, expr|0]
    - match: '\('
      set: [primitive|1, expr|0, primitive|0]
    - match: '\S'
      scope: invalid.illegal.test
      pop: true
  # Rule: primitive
  primitive|1:
    - match: '\)'
      pop: true
    - match: '\S'
      scope: invalid.illegal.test
      pop: true
```
</details>

The first `1` matches in `main`, and then `expr|0` is set; the `(` matches `'(?=\S)'` in `expr|0` which pops the stack (which only contains `expr|0`), resetting back to `main`.

I'm only mostly sure that there's a bug here;  it's possible I have a misunderstanding somewhere. I'll also note that what I _wanted_ to write was actually something like:
```sbnf
main = expr;
expr = expr `+` expr
     | primitive
     ;
primitive = num | `(` expr `)`;
num = '\d+'{constant.numeric};
```
That's because I'm trying to directly translate a yacc source file which contains things like the latter. sbnf overflows the stack if I try it, but compiles my workaround. I hope there's some workaround I can use!

Thanks for taking the report!
