### ISSUE TITLE
'#' translates to ''

### ISSUE THREAD

**Issue by AmjadHD** [BenjaminSchaaf/sbnf#29]
```
main : '#';
```
translates to:
```yaml
main:
  - match: ''
    pop: true
  - match: '\S'
    scope: invalid.illegal.test
```
`` `#` `` and `'######'`  translate correctly.
